version: '3.8'

services:
  nginx:
    container_name: ng_${PROJECT_NAME}
    network_mode: bridge
    restart: always
    env_file: .env
    build:
      context:
        ./etc/nginx
      args:
        - ENV=develop
    ports:
      - ${WEBAPP_PORT}:80
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - NGINX_TIMEOUT=${NGINX_TIMEOUT}
    depends_on:
      - node
    volumes:
      - ./etc/nginx/develop.conf:/etc/nginx/conf.d/mysite.template
      - ./public:/public
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_TIMEOUT $$FRONTEND_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  node:
    container_name: node.${PROJECT_NAME}
    network_mode: bridge
    image: node:14.16
    restart: always
    volumes:
      - ./:/data
    ports:
        - ${NODE_PORT}:3000
        - 3001:3001
    command: /bin/sh -c "cd /data/frontend && npm i && node node_modules/esbuild/install.js && npm run build && cd /data/server/ && npm i && npm run build && cd /data/server/dist/ && node index.js"
    expose:
      - "3000"
      - "3001"
